version: "3.1"
volumes:
  grafana:
  postgres:
services:
  agent:
    image: grafana/agent:v0.35.2
    ports:
      - "4318:4318"
    volumes:
      - "./agent/config.yaml:/etc/agent/agent.yaml"
  dummy-server:
    build: ./src
    ports:
      - "4000:4000"
      - "80:80"
    depends_on:
      - tempo
      - loki
  grafana:
    image: grafana/grafana:10.0.3
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
  loki:
    image: grafana/loki:2.8.3
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo:2.1.1
    ports:
      - "4317:4317"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
